[package]
name = "snt"
version = "0.1.0"
edition = "2024"

[dependencies]
default-net = "0.22.0"
dns-lookup = "2.0.4"
is-wsl = "0.4.0"
tokio = {version = "1.42.0", features = ["rt", "rt-multi-thread", "time", "macros"] }
tracert = "0.8.0"
